services:
  db:
    image: mysql:9.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    container_name: equipos
    volumes:
      - ./mysql:/var/lib/mysql